version: '3.8'

services:
  web1:
    image: myapp:latest
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - DB_PATH=/data/myapp.db
    volumes:
      - /home/ec2-user/db:/data
  web2:
    image: myapp:latest
    ports:
      - "8082:8080"
    environment:
      - PORT=8080
      - DB_PATH=/data/myapp.db
    volumes:
      - /home/ec2-user/db:/data
